---
- name: Setup Swarm Workers
  vars_prompt:
    - name: manager_ip
      prompt: "Manager IP"
      private: false
  hosts: kasm-managers
  become: true
  become_user: root
  roles:
    - docker
  tasks:
    - name: Confirm Packages
      ansible.builtin.apt:
        name: [python3-pip, sshpass, letsencrypt]
        update_cache: true
    - name: Install Docker Module
      ansible.builtin.pip:
        name: [docker, rich]
    - name: Pull Kasm-Manager Repo
      ansible.builtin.git:
        clone: true
        repo: https://github.com/The-Taggart-Institute/kasm-manager
        dest: /home/kasm/kasm-manager
    - name: Init Swarm
      community.docker.docker_swarm:
        state: present
        advertise_addr: "{{ manager_ip }}"
    - name: Pull Terminal Image
      community.docker.docker_image:
        source: pull
        name: taggarttech/tti-kasm-terminal
    - name: Pull Kali Image
      community.docker.docker_image:
        source: pull
        name: taggarttech/tti-kasm-kali
    - name: Add Kasm to Docker
      ansible.builtin.user:
        name: kasm
        groups: [docker]