---
- name: Setup Swarm Workers
  vars_prompt:
    - name: manager_ip
      prompt: "Manager IP"
      private: false
    - name: swarm_token
      prompt: "Swarm Token"
      private: false
  hosts: kasm-workers
  become: true
  become_user: root
  tasks:
    - name: Confirm Pip
      ansible.builtin.apt:
        name: python3-pip
        update_cache: true
    - name: Install Docker Module
      ansible.builtin.pip:
        name: docker
    - name: Join Swarm
      ansible.builtin.shell:
        cmd: "docker swarm join --token {{swarm_token}} {{manager_ip}}:2377"
    - name: Pull Terminal Image
      community.docker.docker_image:
        source: pull
        name: taggarttech/tti-kasm-terminal
    - name: Pull Kali Image
      community.docker.docker_image:
        source: pull
        name: taggarttech/tti-kasm-kali
